junit: 4.8.2

gems:
  #- ci_reporter
  - buildr = 1.4.6

repositories:
  remote:
   - http://repository.jboss.org/nexus/content/groups/public
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://www.ibiblio.org/maven2
   - http://download.java.net/maven/glassfish
   - http://mirror.aarnet.edu.au/pub/eclipse/rt/eclipselink/maven.repo
   - http://www.smartclient.com/maven2

artifacts:
  javax_servlet: javax.servlet:servlet-api:jar:2.5
  appengine_api: com.google.appengine:appengine-api-1.0-sdk:jar:1.5.3
